### ISSUE TITLE
Куда нужно вставить токены и остальное?

### ISSUE THREAD

**Issue by FlameProfi** [07artem132/whmcs-notification-ticket-telegram-hooks#1]
Где найти настройки ?

**Comment by 07artem132** [comment]
Добрый день, вставлять необходимо в настройки модуля (после активации).

**Comment by FlameProfi** [comment]
Подскажите пожалуйста, где именно его активировать и настроить

**Comment by 07artem132** [comment]
В панели администратора whmcs во вкладку "дополнения", обычно это "admin/configaddonmods.php"

**Comment by FlameProfi** [comment]
![image](https://user-images.githubusercontent.com/57589034/116861467-cedade00-ac0b-11eb-846a-f7581435f51b.png)![image](https://user-images.githubusercontent.com/57589034/116861468-cedade00-ac0b-11eb-8670-5b3b174e97a3.png)

**Comment by 07artem132** [comment]
whmcs не видит данный модуль, вероятно название папки не соответствует "NotificationTicketTelegram"

**Comment by FlameProfi** [comment]
странно, название папки именно такое

**Comment by 07artem132** [comment]
Уточните полный путь, куда вы скачали репозиторий и какие файлы находятся по вашему пути.
